### PR TITLE
hardware video acceleration

### PR DESCRIPTION
**Pull request by evenbecker**
new docs entry: hardware setup >> hardware video acceleration

### CODE REVIEW

**Comment by demmm** [comment]
Make sure you create a document for KaOS, seems this is written for another OS, mesa is not split here, so no need to add anything for AMD/ATI.

**Comment by evenbecker** [comment]
Ok, I have updated my commit.

**Comment by demmm** [comment]
Including a link to an article that for the most part will only confuse, since it is not at all related to KaOS packages should not be done. Better use a much more generic link like https://en.wikipedia.org/wiki/Graphics_processing_unit#GPU_accelerated_video_decoding_and_encoding

**Comment by evenbecker** [comment]
I know that Arch is not related to KaOS but some things are well explained in the Arch wiki. Even the Gentoo wiki refers sometimes to the Arch wiki, like [here](https://wiki.gentoo.org/wiki/Compose_key).

**Comment by demmm** [comment]
This is nothing against the Arch wiki, just this article should not be linked for the KaOS users you are targeting.

**Comment by evenbecker** [comment]
ok, I have put the wikipedia

**Pull request merged**
