### PR TITLE
Create dm_crypt-luks.md

### PR DESCRIPTION
**Pull request by zynexiz**
Guide how to encrypt home partition.

### CODE REVIEW

**Comment by demmm** [comment]
To make it work with the website you will need to have frontend matter as the header of the .md file, example (front matter is up to the toc line:
https://raw.githubusercontent.com/KaOSx/kaosx.github.io/master/_docs/kernels.md
That way your name can be included as the author and so on.
Website is generated using jekyll, so the new page also needs to be added [here](https://github.com/KaOSx/kaosx.github.io/blob/master/_data/docs.yml#L22)

Do you want to add to this pull request or prefer I do the needed changes?

**Comment by zynexiz** [comment]
I can do it, better to do it myself to learn how it works ☺

**Comment by zynexiz** [comment]
Added the header. The only part i didn't know what to enter was the worpress one.

**Comment by zynexiz** [comment]
I created a new pull request from a new fork I made. Somehow I managed to create a sub branch under master, got me a bit confused :) I close this one so you can use the other instead. I added the header there to. Github is new to me, but starting to figure out how things work here :)

**Pull request closed without merging**
